
  kecamatan_pasien: 'Bubutan',
  total_pasieny: 1929
}, {
  kecamatan_pasien: 'Bulak',
  total_pasieny: 2022
}, {
  kecamatan_pasien: 'Genteng',
  total_pasieny: 1364
}, {
  kecamatan_pasien: 'Gubeng',
  total_pasieny: 2680
}, {
  kecamatan_pasien: 'Kenjeran',
  total_pasieny: 4410
}, {
  kecamatan_pasien: 'Mulyorejo',
  total_pasieny: 2655
}, {
  kecamatan_pasien: 'Rungkut',
  total_pasieny: 4503
}, {
  kecamatan_pasien: 'Sawahan',
  total_pasieny: 1495
}, {
  kecamatan_pasien: 'Simokerto',
  total_pasieny: 1473
}, {
  kecamatan_pasien: 'Sukolilo',
  total_pasieny: 2948
}, {
  kecamatan_pasien: 'Tambaksari',
  total_pasieny: 4339
}, {
  kecamatan_pasien: 'Tegalsari',
  total_pasieny: 1456
}, {
  kecamatan_pasien: 'Tenggilis',
  total_pasieny: 177
}, {
  kecamatan_pasien: 'Wiyung',
  total_pasieny: 129
}, {
  kecamatan_pasien: 'Wonocolo',
  total_pasieny: 129
}, {
  kecamatan_pasien: 'Wonokromo',
  total_pasieny: 129
}, {
  kecamatan_pasien: 'Wonokromo',
  total_pasieny: 2021
}]